apiVersion: v1
kind: Service
metadata:
  labels:
    app: patient-details
  name: patient-details
  namespace: patient-details
spec:
  ports:
  - port: 5001
    protocol: TCP
    targetPort: 5001
  selector:
    app: patient-details