apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: telemedicinebff-circuit-breaker
  namespace: telemedicinebff
spec:
  host: telemedicinebff
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 1
      http:
        http1MaxPendingRequests: 1
        maxRequestsPerConnection: 1
    outlierDetection:
      consecutiveGatewayErrors: 1
      interval: 1.000s
      baseEjectionTime: 180.000s
      maxEjectionPercent: 100