apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: compositeop-abort
  namespace: <PROJECT> 
spec:
  hosts:
  - compositeop
  http:
  - fault:
      abort:
        httpStatus: 500
        percent: 100
    route:
    - destination:
        host: compositeop
        subset: v1
      weight: 100        
  - route:
    - destination:
        host: compositeop
        subset: v2