apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: patient-database
  name: patient-database
  namespace: <PROJECT>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-database
  template:
    metadata:
      labels:
        app: patient-database
    spec:
      containers:
      - image: shruthiarun23/patient-database
        name: patient-database
        