apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-imaging-deployment
  labels:
    app: patient-imaging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-imaging
  template:
    metadata:
      labels:
        app: patient-imaging
    spec:
      containers:
      - name
