apiVersion: v1
kind: Service
metadata:
  labels:
    app: patient-database
  name: patient-database
  namespace: <PROJECT>
spec:
  ports:
  - port: 5001
    protocol: TCP
    targetPort: 5001
  selector:
    app: patient-database