apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: dose-watch
  name: dose-watch
  namespace: dose-watch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dose-watch
  template:
    metadata:
      labels:
        app: dose-watch
      annotations:
        inject.istio.io/templates: "sidecar,spire"        
    spec:
      containers:
      - image: shruthiarun23/dosewatch
        name: dosewatch
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: db-secret-credentials
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: db-secret-credentials
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: db-secret-credentials
              key: POSTGRES_PASSWORD
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: db-secret-credentials
              key: POSTGRES_PORT
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: db-secret-credentials
              key: POSTGRES_HOST

