apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    module: orthanc
  name: orthanc-pvc
  namespace: telemedicine
spec:  
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi