apiVersion: v1
kind: Service
metadata:
  labels:
    app: patient-imaging
  name: patient-imaging
  namespace: patient-imaging
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: patient-imaging