apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: fixeddelay
  namespace: <PROJECT>  
spec:
  hosts:
  - compositeop
  http:
  - fault:
      delay:
        percent: 100
        fixedDelay: 30s
    route:
    - destination:
        host: compositeop
        subset: v1