apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: telemedicinebff-abort
  namespace: telemedicinebff
spec:
  hosts:
  - telemedicinebff
  http:
  - fault:
      abort:
        httpStatus: 500
        percentage: 
          value: 100
    route:
    - destination:
        host: telemedicinebff
        subset: v1
      weight: 100        
  