apiVersion: v1
kind: Service
metadata:
  name: telemedicinebff
  namespace: telemedicinebff
  labels:
    app: telemedicinebff
spec:
  ports:
    - port: 5000
      targetPort: 5000
      name: http
  selector:
    app: telemedicinebff