apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: fixeddelay
  namespace: telemedicinebff 
spec:
  hosts:
  - telemedicinebff
  http:
  - fault:
      delay:
        percent: 100
        fixedDelay: 30s
    route:
    - destination:
        host: telemedicinebff
        subset: v1