apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: patient-imaging
  name: patient-imaging
  namespace: telemedicine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-imaging
  template:
    metadata:
      labels:
        app: patient-imaging
    spec:
      containers:
      - image: shruthiarun23/patient-imaging
        name: patient-imaging
        