apiVersion: v1
# Kind for kubernets ConfigMap
kind: ConfigMap
metadata:
  # Name your ConfigMap
  name: db-secret-credentials
  namespace: patient-details
  labels:
    app: pd-postgresdb
data:
  # User DB
  POSTGRES_DB: patient_details
  # Db user
  POSTGRES_USER: postgres
  # Db password
  POSTGRES_PASSWORD: scorose23
  #Db port
  POSTGRES_PORT : "5432"
  #Db host
  POSTGRES_HOST : pd-postgresdb