apiVersion: v1
# Kind for kubernets ConfigMap
kind: ConfigMap
metadata:
  # Name your ConfigMap
  name: db-secret-credentials
  namespace: dose-watch
  labels:
    app: dw-postgresdb
data:
  # User DB
  POSTGRES_DB: medicine_dosage
  # Db user
  POSTGRES_USER: postgres
  # Db password
  POSTGRES_PASSWORD: scorose23
  #Db port
  POSTGRES_PORT : "5432"
  #Db host
  POSTGRES_HOST : dw-postgresdb