apiVersion: v1
kind: Service
metadata:
  name: orthanc
  namespace : telemedicine
  labels:
    app.kubernetes.io/name: orthanc   
spec:
  selector:
    module: orthanc
  type: ClusterIP
  ports:
    - name: http
      port: 8042
      targetPort: 8042
      protocol: TCP
    - name: https
      port: 4242
      targetPort: 4242
      protocol: TCP