apiVersion: v1
# Kind for volume chain
kind: PersistentVolume
metadata:
  # Name the persistent chain
  name: dw-postgresdb-persistent-volume
  namespace: dose-watch
  # Labels for identifying PV
  labels:
    type: local
    app: dw-postgresdb
spec:
  storageClassName: manual
  capacity:
    # PV Storage capacity
    storage: 8Gi
  # A db can write and read from volumes to multiple pods
  accessModes:
    - ReadWriteOnce
  # Specify the path to persistent the volumes  
  hostPath:
    path: "/data/dw-db"