apiVersion: v1
kind: Service
metadata:
  labels:
    app: dose-watch
  name: dose-watch
  namespace: <PROJECT>
spec:
  ports:
  - port: 5001
    protocol: TCP
    targetPort: 5001
  selector:
    app: dose-watch