apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: telemedicinebff-ts3
  namespace: telemedicinebff
spec:
  hosts:
    - telemedicinebff
  http:
  - match:
    - headers:
        version:
          exact: v2
    route:
    - destination:
        host: telemedicinebff
        subset: v2
  - route:
    - destination:
        host: telemedicinebff
        subset: v1