apiVersion: v1
# Kind for volume chain
kind: PersistentVolume
metadata:
  # Name the persistent chain
  name: pd-postgresdb-persistent-volume
  namespace: patient-details
  # Labels for identifying PV
  labels:
    type: local
    app: pd-postgresdb
spec:
  storageClassName: manual
  capacity:
    # PV Storage capacity
    storage: 8Gi
  # A db can write and read from volumes to multiple pods
  accessModes:
    - ReadWriteOnce
  # Specify the path to persistent the volumes  
  hostPath:
    path: "/data/pd-db"