apiVersion: v1
# define a resource for volume chain
kind: PersistentVolumeClaim
metadata:
  # Name the volume chain
  name: pd-db-persistent-volume-claim
  namespace: patient-details
spec:
  storageClassName: manual
  accessModes:
    # Allow ReadWrite to multiple pods
    - ReadWriteOnce
  # PVC requesting resources
  resources:
    requests:
      # the PVC storage
      storage: 8Gi